### Auth Server
GET http://localhost:4000/api/v1/user/home
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmY2RjMWRkN2QxZDcwMTc4ODcwOTIzNyIsImVtYWlsIjoiYWRtaW5AaG9tZS5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MDczMjIxOTMsImV4cCI6MTYwNzQwODU5M30.hdyJUY1kRtN8MRz_QXhN_qdKU2K0P7D-fqUPX7bqb6

### All users
GET http://localhost:4000/api/v1/auth/all

### Add User
POST http://localhost:4000/api/v1/auth/signup
Content-Type: application/json

{
    "email": "admin@home.com",
    "password": "password",
    "isAdmin": true
}

### Login the user
POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@home.com",
    "password": "password"
}

###
DELETE http://localhost:4000/api/v1/auth/logout


