### Auth Server
GET http://localhost:4000/api/v1/user/home
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmY2RjMWRkN2QxZDcwMTc4ODcwOTIzNyIsImVtYWlsIjoiYWRtaW5AaG9tZS5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MDczMjg0NDAsImV4cCI6MTYwNzQxNDg0MH0.dAVTy7HWZwOMhkdxA_a5JQQtdIz3d6EztmBDE71AaR4; Path=/; Expires=Mon, 07 Dec 2020 08:07:20 GMT; HttpOnly

### All users
GET http://localhost:4000/api/v1/auth/all

### Add User
POST http://localhost:4000/api/v1/auth/signup
Content-Type: application/json

{
    "email": "admin@home.com",
    "password": "password",
    "isAdmin": true
}

### Login the user
POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@home.com",
    "password": "password"
}

###
DELETE http://localhost:4000/api/v1/auth/logout


